import {
  pillow,
  shorts,
  hat,
  toteWhite,
  toteBlack,
  toteWhiteModel,
  toteBlackModel,
  shirtBlack,
  shirtBlue,
  popsicleShirtBlack,
  popsicleShirtWhite,
  popsicleShirtBlackModel,
  otherHoodieBlack,
  otherHoodieGreen,
  otherHoodieOrange,
  otherHoodieWhite,
  crewneckGrey,
  crewneckNavyBlue,
  colorfulHoodieBlue,
  colorfulHoodieBlueModel,
  colorfulHoodieRed,
  colorfulHoodieRedModel,
  colorfulHoodieYellow,
  colorfulHoodieYellowModel,
} from "./StoreImages";

export const storeItems = [
  {
    id: 1,
    img: otherHoodieBlack,
    product: "Other Hoodie (Black)",
    price: "$60.00",
    modelImg: "",
  },
  {
    id: 2,
    img: otherHoodieGreen,
    product: "Other Hoodie (Green)",
    price: "$60.00",
    modelImg: "",
  },
  {
    id: 3,
    img: otherHoodieOrange,
    product: "Other Hoodie (Orange)",
    price: "$60.00",
    modelImg: "",
  },
  {
    id: 4,
    img: otherHoodieWhite,
    product: "Other Hoodie (White)",
    price: "$60.00",
    modelImg: "",
  },
  {
    id: 5,
    img: popsicleShirtWhite,
    product: "Popsicle Shirt (White)",
    price: "$35.00",
    modelImg: "",
  },

  {
    id: 6,
    img: popsicleShirtBlack,
    product: "Popsicle Shirt (Black)",
    price: "$35.00",
    modelImg: popsicleShirtBlackModel,
  },
  {
    id: 7,
    img: shirtBlack,
    product: "Shirt (Black)",
    price: "$30.00",
    modelImg: popsicleShirtBlackModel,
  },
  {
    id: 8,
    img: shirtBlue,
    product: "Shirt (Blue)",
    price: "$30.00",
    modelImg: "",
  },
  {
    id: 9,
    img: crewneckNavyBlue,
    product: "Crewneck (Navy Blue)",
    price: "$45.00",
    modelImg: "",
  },
  {
    id: 10,
    img: crewneckGrey,
    product: "Crewneck (Grey)",
    price: "$45.00",
    modelImg: "",
  },
  {
    id: 11,
    img: colorfulHoodieBlue,
    product: "Colorful Hoodie (Blue)",
    price: "$70.00",
    modelImg: colorfulHoodieBlueModel,
  },
  {
    id: 12,
    img: colorfulHoodieRed,
    product: "Colorful Hoodie (Red)",
    price: "$70.00",
    modelImg: colorfulHoodieRedModel,
  },
  {
    id: 13,
    img: colorfulHoodieYellow,
    product: "Colorful Hoodie (Yellow)",
    price: "$70.00",
    modelImg: colorfulHoodieYellowModel,
  },
  {
    id: 14,
    img: shorts,
    product: "Shorts",
    price: "$35.00",
    modelImg: "",
  },

  {
    id: 15,
    img: pillow,
    product: "Pillow",
    price: "$20.00",
    modelImg: "",
  },
  {
    id: 16,
    img: hat,
    product: "Hat",
    price: "$15.00",
    modelImg: "",
  },
  {
    id: 17,
    img: toteBlack,
    product: "Tote (Black)",
    price: "$25.00",
    modelImg: toteBlackModel,
  },
  {
    id: 18,
    img: toteWhite,
    product: "Tote (Black)",
    price: "$25.00",
    modelImg: toteWhiteModel,
  },
];
